export default [
  {
    id: "0ca88a56-a19a-11eb-bcbc-0242ac130002",
    content: {
      blocks: [
        {
          key: "9tik9",
          text: "Scriber",
          type: "header-one",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 12,
              style: "UNDERLINE",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "99hbq",
          text: "A simple and minimal note taking application.",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "9vkn4",
          text: "Some of the things Scriber is capable of:",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 44,
              style: "ITALIC",
            },
            {
              offset: 19,
              length: 10,
              style: "BOLD",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "ev32c",
          text: "Different headings (Title, Heading, Body).",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "6nun7",
          text: "Inline styles such as bold, italic, underline, highlight, strikethrough and code.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 22,
              length: 4,
              style: "BOLD",
            },
            {
              offset: 28,
              length: 6,
              style: "ITALIC",
            },
            {
              offset: 36,
              length: 9,
              style: "UNDERLINE",
            },
            {
              offset: 47,
              length: 9,
              style: "HIGHLIGHT",
            },
            {
              offset: 58,
              length: 13,
              style: "STRIKETHROUGH",
            },
            {
              offset: 76,
              length: 4,
              style: "CODE",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "31dou",
          text: "Lists, including unordered & ordered lists.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "5b657",
          text: "Quotes and codeblocks.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "enrri",
          text: "Blockquotes 📢",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "6plpk",
          text: '"Write a beautiful quote here" -Bob The Builder',
          type: "blockquote",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "c2dbd",
          text: "Codeblocks 🖥",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "3st99",
          text: "toggleBlockType(blockType) {\n  this.onChange(\n    RichUtils.toggleBlockType(\n      this.state.editorState, blockType\n    )\n  );\n}",
          type: "code-block",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "clgmo",
          text: "List Example",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "585a2",
          text: "task1",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {
            checked: true,
          },
        },
        {
          key: "6deno",
          text: "task2",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 22,
              style: "STRIKETHROUGH",
            },
          ],
          entityRanges: [],
          data: {
            checked: false,
          },
        },
        {
          key: "addu1",
          text: "task3",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {
            checked: false,
          },
        },
        {
          key: "5n6n5",
          text: "task4",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "c7lff",
          text: "Example:",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "5eb16",
          text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sollicitudin turpis tellus, eget fermentum est dignissim at. Phasellus aliquet, augue nec molestie interdum, felis nibh facilisis dui, id elementum magna augue nec ex. Quisque semper ut ipsum in pulvinar. Suspendisse potenti. Mauris in rhoncus urna, sed posuere risus. Phasellus efficitur odio sit amet massa egestas posuere. Donec varius neque a magna tincidunt, ac rhoncus quam lobortis. Nunc sit amet massa venenatis, fringilla lorem sit amet, sodales augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris sed facilisis massa, nec blandit elit. Etiam massa nulla, tincidunt non enim imperdiet, tempor iaculis magna. Vivamus rutrum pharetra commodo. Praesent volutpat orci maximus, tincidunt nisl id, fringilla lacus.",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 59,
              style: "HIGHLIGHT",
            },
            {
              offset: 100,
              length: 6,
              style: "BOLD",
            },
            {
              offset: 254,
              length: 26,
              style: "BOLD",
            },
            {
              offset: 135,
              length: 16,
              style: "UNDERLINE",
            },
            {
              offset: 254,
              length: 26,
              style: "UNDERLINE",
            },
            {
              offset: 198,
              length: 6,
              style: "ITALIC",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "atj88",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "8djjp",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "2gmtp",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "fhg86",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "1bgk3",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "39qol",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "djld",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
      ],
      entityMap: {},
    },
  },
];
